micronaut:
  application:
    name: backend
  security:
    intercept-url-map:
    - pattern: /swagger/**
      access: isAnonymous()
    - pattern: /swagger-ui/**
      access: isAnonymous()
    authentication: session
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
flyway:
  datasources:
    default:
      enabled: true
jpa.default.properties.hibernate.hbm2ddl.auto: none
