micronaut:
  application:
    name: backend
  server:
    port: 8080
    cors:
      enabled: true
  security:
    intercept-url-map:
      - pattern: /swagger/**
        access: isAnonymous()
      - pattern: /swagger-ui/**
        access: isAnonymous()
    authentication: session
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
#datasources:
#  default:
#    driver-class-name: org.postgresql.Driver
#    db-type: postgres
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/fitapp
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    username: fitapp
    password: fitapppassword
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true
